/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 michelly.glb -t 
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import { GroupProps } from '@react-three/fiber';
import { useEffect } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Ch03: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    Ch03_Body: THREE.MeshStandardMaterial;
  };
};

type AnimationResult = GLTF;

interface MichellyModelProps extends GroupProps {
  currentAnimation?: 'IDLE' | 'WALKING';
}

export function MichellyModel({ ...props }: MichellyModelProps) {
  const gltf = useGLTF('./models/michelly.glb') as GLTFResult;

  const { materials } = gltf;

  materials.Ch03_Body.depthWrite = true;

  gltf.scene.traverse((e) => {
    e.castShadow = true;
  });

  return (
    <group {...props}>
      <primitive object={gltf.scene} />
      {gltf.scene && <AddAnimations scene={gltf.scene} />}
    </group>
  );
}

interface AddAnimationProps {
  scene: THREE.Group;
}

const AddAnimations = ({ scene }: AddAnimationProps) => {
  const { animations } = useGLTF('./animations/walking.glb') as AnimationResult;
  const { actions } = useAnimations(animations, scene);

  useEffect(() => {
    actions['Armature|mixamo.com|Layer0']?.play();
  }, []);
  return null;
};

useGLTF.preload('./animations/walking.glb');
useGLTF.preload('./models/michelly.glb');

export default MichellyModel;
