/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 rato.glb 
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import { GroupProps } from '@react-three/fiber';
import { useEffect } from 'react';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';

type GLTFResult = GLTF & {
  nodes: {
    Ch14: THREE.SkinnedMesh;
    mixamorig1Hips: THREE.Bone;
  };
  materials: {
    Ch14_Body: THREE.MeshStandardMaterial;
  };
};

type AnimationResult = GLTF;

interface RatoModelProps extends GroupProps {
  currentAnimation?: 'IDLE' | 'WALKING';
}

export function RatoModel({ ...props }: RatoModelProps) {
  const gltf = useGLTF('./models/rato.glb') as GLTFResult;

  const { materials } = gltf;

  materials.Ch14_Body.depthWrite = true;

  gltf.scene.traverse((e) => {
    e.castShadow = true;
  });

  return (
    <group {...props}>
      <primitive object={gltf.scene} />
      {gltf.scene && <AddAnimations scene={gltf.scene} />}
    </group>
  );
}

interface AddAnimationProps {
  scene: THREE.Group;
}

const AddAnimations = ({ scene }: AddAnimationProps) => {
  const { animations } = useGLTF('./animations/walking.glb') as AnimationResult;
  const { actions } = useAnimations(animations, scene);

  console.log(actions);

  useEffect(() => {
    actions['Armature|mixamo.com|Layer0']?.play();
  }, []);
  return null;
};

useGLTF.preload('./models/rato.glb');
useGLTF.preload('./animations/idle.glb');
useGLTF.preload('./animations/walking.glb');

export default RatoModel;
